# Generated by Django 6.0.4 on 2026-04-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_admin_notes_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Référence commande')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MAD)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('declined', 'Refusé'), ('error', 'Erreur'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('method', models.CharField(choices=[('cmi', 'CMI (Carte bancaire marocaine)'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('simulation', 'Test / Simulation')], default='cmi', max_length=20, verbose_name='Méthode')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID Transaction CMI')),
                ('auth_code', models.CharField(blank=True, max_length=50, verbose_name='Code autorisation')),
                ('response_code', models.CharField(blank=True, max_length=10, verbose_name='Code réponse CMI')),
                ('response_message', models.TextField(blank=True, verbose_name='Message réponse')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres carte')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='Type carte')),
                ('raw_response', models.TextField(blank=True, verbose_name='Réponse brute CMI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
