# Generated by Django 6.0.4 on 2026-04-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la chambre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit (MAD)')),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('prestige', 'Prestige')], default='standard', max_length=20, verbose_name='Catégorie')),
                ('capacity', models.IntegerField(default=2, verbose_name='Capacité (personnes)')),
                ('size', models.IntegerField(default=25, verbose_name='Superficie (m²)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Image principale')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcon')),
                ('has_sea_view', models.BooleanField(default=False, verbose_name='Vue mer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='rooms/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_360', models.BooleanField(default=False, verbose_name='Image 360°')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Image de chambre',
                'verbose_name_plural': 'Images de chambre',
                'ordering': ['order'],
            },
        ),
    ]
