# Generated by Django 6.0.4 on 2026-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/gallery/', verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Image principale (upload)'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL image externe (Unsplash, etc.)'),
        ),
    ]
