# Generated by Django 6.0.4 on 2026-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomimage_image_file_alter_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_bathtub',
            field=models.BooleanField(default=False, verbose_name='Baignoire'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False, verbose_name='Mini-bar'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_safe',
            field=models.BooleanField(default=True, verbose_name='Coffre-fort'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, verbose_name='TV'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL image externe'),
        ),
    ]
