# Generated by Django 6.0.4 on 2026-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_has_bathtub_room_has_minibar_room_has_safe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_config',
            field=models.CharField(blank=True, help_text='Ex: 1 lit double ou 2 lits simples', max_length=300, verbose_name='Configuration des lits'),
        ),
        migrations.AddField(
            model_name='room',
            name='free_cancellation',
            field=models.BooleanField(default=True, verbose_name='Annulation gratuite'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_garden_view',
            field=models.BooleanField(default=False, verbose_name='Vue sur jardin'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_pool_view',
            field=models.BooleanField(default=False, verbose_name='Vue sur piscine'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_private_bathroom',
            field=models.BooleanField(default=True, verbose_name='Salle de bains privative'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_soundproofing',
            field=models.BooleanField(default=False, verbose_name='Insonorisation'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='Terrasse'),
        ),
        migrations.AddField(
            model_name='room',
            name='includes_breakfast',
            field=models.BooleanField(default=True, verbose_name='Petit-déjeuner inclus'),
        ),
        migrations.AddField(
            model_name='room',
            name='includes_parking',
            field=models.BooleanField(default=True, verbose_name='Parking inclus'),
        ),
        migrations.AddField(
            model_name='room',
            name='no_prepayment',
            field=models.BooleanField(default=True, verbose_name='Aucun prépaiement requis'),
        ),
        migrations.AddField(
            model_name='room',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix barré (avant réduction)'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_count',
            field=models.IntegerField(default=1, verbose_name='Nombre de chambres de ce type'),
        ),
    ]
