# Generated by Django 6.0.4 on 2026-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(default="L'Art de", max_length=200, verbose_name='Titre ligne 1')),
                ('title_line2', models.CharField(default="l'Hospitalité", max_length=200, verbose_name='Titre ligne 2 (grande)')),
                ('title_line3', models.CharField(default='Marocaine', max_length=200, verbose_name='Titre ligne 3')),
                ('subtitle', models.TextField(default='Découvrez une oasis de raffinement au cœur de Casablanca.', verbose_name='Sous-titre')),
                ('badge_text', models.CharField(default='★★★★★ · Casablanca · Depuis 1985', max_length=200, verbose_name='Badge texte')),
                ('bg_image_url', models.URLField(blank=True, max_length=500, verbose_name='URL image de fond')),
                ('bg_image_file', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Upload image de fond')),
                ('btn_primary_text', models.CharField(default='Découvrir nos Suites', max_length=100, verbose_name='Bouton principal texte')),
                ('btn_secondary_text', models.CharField(default='Réserver', max_length=100, verbose_name='Bouton secondaire texte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Section Hero',
                'verbose_name_plural': 'Sections Hero',
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Al Andalus', max_length=200, verbose_name="Nom de l'hôtel")),
                ('tagline', models.CharField(default='HOTEL & SPA · CASABLANCA', max_length=300, verbose_name='Slogan')),
                ('about_title', models.CharField(default="Un Héritage d'Excellence au Cœur du Maroc", max_length=200, verbose_name='Titre section À propos')),
                ('about_text1', models.TextField(default="Fondé en 1985 sur les rives de l'Atlantique, l'Hôtel Al Andalus s'est imposé comme le symbole du raffinement marocain.", verbose_name='Texte à propos paragraphe 1')),
                ('about_text2', models.TextField(blank=True, verbose_name='Texte à propos paragraphe 2')),
                ('about_image_url', models.URLField(blank=True, max_length=500, verbose_name='URL image à propos principale')),
                ('about_image_file', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Upload image à propos')),
                ('founded_year', models.IntegerField(default=1985, verbose_name='Année de fondation')),
                ('address', models.TextField(default='Boulevard de la Corniche, Casablanca 20000', verbose_name='Adresse')),
                ('phone', models.CharField(default='+212 5 22 XX XX XX', max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@hotel-alandalus.ma', max_length=254, verbose_name='Email')),
                ('checkin_time', models.CharField(default='14h00', max_length=10, verbose_name='Heure check-in')),
                ('checkout_time', models.CharField(default='12h00', max_length=10, verbose_name='Heure check-out')),
                ('stars', models.IntegerField(default=5, verbose_name="Nombre d'étoiles")),
                ('total_rooms', models.IntegerField(default=38, verbose_name='Nombre total de chambres')),
                ('satisfaction_rate', models.IntegerField(default=98, verbose_name='Taux de satisfaction (%)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Informations Hôtel',
                'verbose_name_plural': 'Informations Hôtel',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_class', models.CharField(default='fas fa-concierge-bell', help_text='Ex: fas fa-spa, fas fa-utensils, fas fa-swimming-pool', max_length=100, verbose_name='Classe icône FontAwesome')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL image')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Upload image')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Afficher sur l'accueil")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('origin', models.CharField(default='France', max_length=200, verbose_name='Ville / Pays')),
                ('text', models.TextField(verbose_name='Témoignage')),
                ('rating', models.IntegerField(default=5, verbose_name='Note /5')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Afficher sur l'accueil")),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order'],
            },
        ),
    ]
