# Generated by Django 6.0.4 on 2026-04-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('rooms', '0003_room_has_bathtub_room_has_minibar_room_has_safe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la promotion')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('badge', models.CharField(choices=[('flash', 'Flash Sale'), ('limited', 'Offre Limitée'), ('exclusive', 'Exclusif'), ('seasonal', 'Saisonnier'), ('lastminute', 'Dernière Minute'), ('honeymoon', 'Lune de Miel'), ('business', 'Business')], default='limited', max_length=20, verbose_name='Badge')),
                ('discount_pct', models.IntegerField(default=0, help_text='0 = pas de %, laissez vide', verbose_name='Réduction (%)')),
                ('discount_label', models.CharField(blank=True, help_text="Ex: '-20%', 'Petit-déj offert', '3ème nuit gratuite'", max_length=100, verbose_name='Label réduction')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL image')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Upload image')),
                ('cta_text', models.CharField(default='En profiter', max_length=100, verbose_name='Texte bouton')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valable du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Afficher sur l'accueil")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='rooms.room', verbose_name='Chambre liée (optionnel)')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
