# Generated by Django 6.0.4 on 2026-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_from', models.TimeField(default='14:00', verbose_name='Check-in à partir de')),
                ('checkin_until', models.TimeField(default='23:00', verbose_name="Check-in jusqu'à")),
                ('checkout_from', models.TimeField(default='06:00', verbose_name='Check-out à partir de')),
                ('checkout_until', models.TimeField(default='12:00', verbose_name="Check-out jusqu'à")),
                ('cancellation_policy', models.TextField(default="Annulation gratuite jusqu'à 48 heures avant l'arrivée. Au-delà, la première nuit sera facturée.", verbose_name="Politique d'annulation")),
                ('prepayment_policy', models.TextField(blank=True, default="Un acompte de 30% sera prélevé à la réservation. Le solde est réglé à l'arrivée.", verbose_name='Politique de prépaiement')),
                ('children_allowed', models.BooleanField(default=True, verbose_name='Enfants acceptés')),
                ('children_policy', models.TextField(blank=True, default='Tous les enfants sont les bienvenus. Les enfants de moins de 7 ans séjournent gratuitement. Les enfants de plus de 7 ans sont facturés au tarif adulte.', verbose_name='Conditions enfants')),
                ('baby_cot_available', models.BooleanField(default=True, verbose_name='Lit bébé disponible')),
                ('baby_cot_price', models.CharField(blank=True, default='Gratuit', max_length=50, verbose_name='Prix lit bébé')),
                ('baby_cot_age_range', models.CharField(blank=True, default='0 – 3 ans', max_length=20, verbose_name="Tranche d'âge lit bébé")),
                ('extra_bed_available', models.BooleanField(default=False, verbose_name="Lit d'appoint disponible")),
                ('extra_bed_price', models.CharField(blank=True, max_length=50, verbose_name="Prix lit d'appoint")),
                ('age_restriction', models.BooleanField(default=False, verbose_name="Restriction d'âge à l'enregistrement")),
                ('age_minimum', models.IntegerField(blank=True, default=18, null=True, verbose_name='Âge minimum requis')),
                ('age_restriction_notes', models.TextField(blank=True, default="Aucune restriction relative à l'âge ne s'applique pour l'enregistrement.", verbose_name="Notes restriction d'âge")),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Animaux domestiques acceptés')),
                ('pets_policy', models.TextField(blank=True, default="Les animaux de compagnie ne sont pas admis au sein de l'établissement.", verbose_name='Politique animaux')),
                ('groups_policy', models.TextField(blank=True, default='Toute réservation de plus de 10 chambres peut entraîner des conditions particulières et des frais supplémentaires. Contactez-nous pour un devis personnalisé.', verbose_name='Politique groupes')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Fumeurs autorisés')),
                ('smoking_notes', models.TextField(blank=True, default="Il est strictement interdit de fumer dans toutes les chambres et espaces communs. Des espaces fumeurs sont disponibles à l'extérieur.", verbose_name='Notes fumeurs')),
                ('parties_allowed', models.BooleanField(default=False, verbose_name='Fêtes/événements autorisés')),
                ('parties_notes', models.TextField(blank=True, default='Les fêtes et événements ne sont pas autorisés dans les chambres.', verbose_name='Notes fêtes/événements')),
                ('accepts_visa', models.BooleanField(default=True, verbose_name='Visa')),
                ('accepts_mastercard', models.BooleanField(default=True, verbose_name='Mastercard')),
                ('accepts_amex', models.BooleanField(default=False, verbose_name='American Express')),
                ('accepts_cash', models.BooleanField(default=True, verbose_name='Espèces')),
                ('accepts_cmi', models.BooleanField(default=True, verbose_name='CMI (cartes marocaines)')),
                ('accepts_bank_transfer', models.BooleanField(default=False, verbose_name='Virement bancaire')),
                ('additional_rules', models.TextField(blank=True, verbose_name='Règles supplémentaires')),
            ],
            options={
                'verbose_name': 'Règles de la maison',
                'verbose_name_plural': 'Règles de la maison',
            },
        ),
    ]
