# Generated by Django 6.0.4 on 2026-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_hotelrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('answer_items', models.TextField(blank=True, help_text='Optionnel : une entrée par ligne. Ex:\n- Continental\n- Buffet', verbose_name='Liste à puces (une entrée par ligne)')),
                ('category', models.CharField(choices=[('general', 'Général'), ('checkin', 'Arrivée & Départ'), ('rooms', 'Chambres & Hébergement'), ('services', 'Services & Activités'), ('restaurant', 'Restaurant & Petit-déjeuner'), ('pricing', 'Tarifs & Paiement'), ('location', 'Localisation'), ('family', 'Familles'), ('policies', 'Politiques')], default='general', max_length=20, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('is_featured', models.BooleanField(default=True, verbose_name="Afficher sur l'accueil")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
