# Generated by Django 6.0.4 on 2026-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notre Carte', max_length=200, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description courte')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL image')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Upload image')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carte du restaurant',
                'verbose_name_plural': 'Cartes du restaurant',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
