# Generated by Django 6.0.4 on 2026-04-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_menucard'),
    ]

    operations = [
    ]
