# Generated by Django 6.0.4 on 2026-04-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_hotelinfo_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='about_image_accent_file',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/', verbose_name='Upload petite image accent'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='about_image_accent_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Petite image accent (À Propos)'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='cta_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1920&q=80', max_length=500, verbose_name='Image CTA (section accueil)'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_1_icon',
            field=models.CharField(default='fas fa-leaf', max_length=50, verbose_name='Feature 1 — Icône'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_1_text',
            field=models.CharField(default='Cuisine marocaine authentique', max_length=100, verbose_name='Feature 1 — Texte'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_2_icon',
            field=models.CharField(default='fas fa-spa', max_length=50, verbose_name='Feature 2 — Icône'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_2_text',
            field=models.CharField(default='Spa & Hammam traditionnel', max_length=100, verbose_name='Feature 2 — Texte'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_3_icon',
            field=models.CharField(default='fas fa-swimming-pool', max_length=50, verbose_name='Feature 3 — Icône'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_3_text',
            field=models.CharField(default='Piscine Olympic & Terrasse', max_length=100, verbose_name='Feature 3 — Texte'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_4_icon',
            field=models.CharField(default='fas fa-concierge-bell', max_length=50, verbose_name='Feature 4 — Icône'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature_4_text',
            field=models.CharField(default='Conciergerie 24h/24', max_length=100, verbose_name='Feature 4 — Texte'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='hero_booking_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=1920&q=80', max_length=500, verbose_name='Image hero — Page Réservation'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='hero_detail_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1920&q=80', max_length=500, verbose_name='Image hero — Page Détail Chambre'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='hero_rooms_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1920&q=80', max_length=500, verbose_name='Image hero — Page Chambres'),
        ),
    ]
