# Generated by Django 6.0.4 on 2026-04-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_hotelinfo_about_image_accent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='years_excellence',
            field=models.IntegerField(blank=True, help_text="Laissez vide pour calculer automatiquement depuis l'année de fondation", null=True, verbose_name="Ans d'excellence (optionnel)"),
        ),
    ]
