# Generated by Django 6.0.4 on 2026-04-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('check_in', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out', models.DateField(verbose_name='Date de départ')),
                ('guests', models.IntegerField(default=1, verbose_name='Nombre de personnes')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total (MAD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
